chore: test truncating plan output

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -79,91 +79,96 @@ jobs:
         working-directory: ./terraform
         continue-on-error: true
 
-      - uses: actions/github-script@v4
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      - name: View context attributes
+        uses: actions/github-script@v4
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+          script: console.log(context)
 
-            <details><summary>Show Plan</summary>
+      # - uses: actions/github-script@v4
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-            \`\`\`${process.env.PLAN}\`\`\`
+      #       <details><summary>Show Plan</summary>
 
-            </details>
+      #       \`\`\`${process.env.PLAN}\`\`\`
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       </details>
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-      # NPM PACKAGES
-      - uses: actions/cache@v2
-        with:
-          path: |
-            **/node_modules
-          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
-      - name: Install Yarn dependencies in root
-        run: yarn
+      #       github.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-      - name: Save terraform plan event
-        if: github.event_name == 'pull_request'
-        uses: bcgov/sso-requests-actions/plan@v0.3.0
-        with:
-          github-token: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
-          api-url: "${{env.API_URL}}"
-          auth-secret: ${{ secrets.GH_SECRET }}
-          plan-output: "${{ steps.plan.outputs.stdout }}"
-          plan-result: "${{ steps.plan.outcome }}"
-          pr-number: "${{ github.event.number }}"
-          pr-branch: "${{ github.event.pull_request.head.ref }}"
-          allowed-additions: "21"
-          allowed-deletions: "21"
-          allowed-updates: "21"
-          allowed-file-changes: "3"
+      # # NPM PACKAGES
+      # - uses: actions/cache@v2
+      #   with:
+      #     path: |
+      #       **/node_modules
+      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+      # - name: Install Yarn dependencies in root
+      #   run: yarn
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Save terraform plan event
+      #   if: github.event_name == 'pull_request'
+      #   uses: bcgov/sso-requests-actions/plan@v0.3.0
+      #   with:
+      #     github-token: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
+      #     api-url: "${{env.API_URL}}"
+      #     auth-secret: ${{ secrets.GH_SECRET }}
+      #     plan-output: "${{ steps.plan.outputs.stdout }}"
+      #     plan-result: "${{ steps.plan.outcome }}"
+      #     pr-number: "${{ github.event.number }}"
+      #     pr-branch: "${{ github.event.pull_request.head.ref }}"
+      #     allowed-additions: "21"
+      #     allowed-deletions: "21"
+      #     allowed-updates: "21"
+      #     allowed-file-changes: "3"
 
-      # Below actions only run on push events
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
-        working-directory: ./terraform
-        continue-on-error: true
+      # # Below actions only run on push events
 
-      - name: Get PR Number
-        id: prNumber
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: |
-          pr=$(curl -H "Accept: application/vnd.github.groot-preview+json" https://api.github.com/repos/${{github.repository}}/commits/${{github.sha}}/pulls)
-          number=$(jq ".[0].number" <<< "$pr")
-          fullLabels=$(jq ".[0].labels" <<< "$pr")
-          botLabel=$(jq -c '.[] | select(.name | contains("auto_generated")).name' <<< "$fullLabels")
-          echo "::set-output name=number::$number"
-          echo "::set-output name=botLabel::$botLabel"
+      # - name: Terraform Apply
+      #   id: apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve
+      #   working-directory: ./terraform
+      #   continue-on-error: true
 
-      - name: Update Apply Status
-        uses: fjogeleit/http-request-action@master
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.prNumber.outputs.botLabel == '"auto_generated"'
-        with:
-          url: "${{env.API_URL}}?status=apply"
-          method: "PUT"
-          data: '{"prNumber": ${{ steps.prNumber.outputs.number }}, "applySuccess": "${{steps.apply.outcome != ''failure''}}"}'
-          customHeaders: '{"Authorization": "${{secrets.GH_SECRET}}"}'
-          timeout: "60000"
+      # - name: Get PR Number
+      #   id: prNumber
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: |
+      #     pr=$(curl -H "Accept: application/vnd.github.groot-preview+json" https://api.github.com/repos/${{github.repository}}/commits/${{github.sha}}/pulls)
+      #     number=$(jq ".[0].number" <<< "$pr")
+      #     fullLabels=$(jq ".[0].labels" <<< "$pr")
+      #     botLabel=$(jq -c '.[] | select(.name | contains("auto_generated")).name' <<< "$fullLabels")
+      #     echo "::set-output name=number::$number"
+      #     echo "::set-output name=botLabel::$botLabel"
 
-      - name: Fail action if apply failed
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.prNumber.outputs.botLabel == '"auto_generated"' && steps.apply.outcome == 'failure'
-        run: exit 1
+      # - name: Update Apply Status
+      #   uses: fjogeleit/http-request-action@master
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.prNumber.outputs.botLabel == '"auto_generated"'
+      #   with:
+      #     url: "${{env.API_URL}}?status=apply"
+      #     method: "PUT"
+      #     data: '{"prNumber": ${{ steps.prNumber.outputs.number }}, "applySuccess": "${{steps.apply.outcome != ''failure''}}"}'
+      #     customHeaders: '{"Authorization": "${{secrets.GH_SECRET}}"}'
+      #     timeout: "60000"
+
+      # - name: Fail action if apply failed
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.prNumber.outputs.botLabel == '"auto_generated"' && steps.apply.outcome == 'failure'
+      #   run: exit 1
